### ISSUE TITLE
Implement header with snapcraft logo for snap details page

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft-flask#15]
Designs: https://github.com/CanonicalLtd/snapcraft-design/issues/54#issuecomment-326014685

**Comment by nottrobin** [comment]
Instead of updating the header in [snapcraft-flask](https://github.com/canonical-websites/snapcraft-flask) to augment the default vanilla navigation pattern with custom styles, we should instead update [snapcraft.io](https://github.com/canonical-websites/snapcraft.io) to use default vanilla styles in the header. I'll create an issue to that effect.
